bugfix: failed to insert records for repeated/json field
To insert records for repeated/json column, BigQuery API expects JSON object.
However the plugin always returns string value and causes following failuer.

---
Error: org.jruby.exceptions.RaiseException: (Error) failed during waiting a Load job, get_job(<project_id>, embulk_load_job_xxxxxx-xxxxx),
errors:[{:reason=>"invalid", :message=>"JSON table encountered too many errors, giving up. Rows: 1; errors: 1.", :location=>"file-00000000"},
{:reason=>"invalid", :message=>"JSON parsing error in row starting at position 0: .
Repeated field must be imported as a JSON array. Field: <repeated_field>.", :location=>" file-00000000"}]
---

This patch removes unnecessary `.to_json` to insert data for repeated/json field.